[versions]
agp = "8.12.3"
media3 = "1.9.0"
ackpine = "0.18.5"

[libraries]
core = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
browser = { module = "androidx.browser:browser", version = "1.9.0" }
preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
webkit = { module = "androidx.webkit:webkit", version = "1.15.0" }
material = { module = "com.google.android.material:material", version = "1.13.0" }

# Ackpine
ackpine-core = { group = "ru.solrudev.ackpine", name = "ackpine-core", version.ref = "ackpine" }
ackpine-ktx = { group = "ru.solrudev.ackpine", name = "ackpine-ktx", version.ref = "ackpine" }

# Exoplayer
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }

# Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.12.2" }
compose-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version = "0.37.3" }

[bundles]
ackpine = ["ackpine-core", "ackpine-ktx"]

exoplayer = ["media3-exoplayer", "media3-exoplayer-dash", "media3-exoplayer-hls",
    "media3-datasource-okhttp", "media3-ui", "media3-session"]

[plugins]
app = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }