[versions]
compose = "1.9.3"
coil = "3.3.0"
navigation = "1.4.3"
jewel = "0.33.0-253.29795"

[libraries]
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version = "1.10.0-alpha05" }
resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "compose" }

jewel-standalone = { group = "org.jetbrains.jewel", name = "jewel-int-ui-standalone", version.ref = "jewel" }
jewel-window = { group = "org.jetbrains.jewel", name = "jewel-int-ui-decorated-window", version.ref = "jewel" }

# Components
confetti = { module = "io.github.vinceglb:confettikit", version = "0.7.0" }
html = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version = "1.1.0" }
haze = { module = "dev.chrisbanes.haze:haze", version = "1.7.1" }
materialKolor = { module = "com.materialkolor:material-kolor", version = "4.0.5" }
tv-material = { module = "androidx.tv:tv-material", version = "1.0.1" }

# Navigation
navigation-core-jvm = { group = "ru.mrboomdev.navigation", name = "navigation-core-jvm", version.ref = "navigation" }
navigation-jetpack = { group = "ru.mrboomdev.navigation", name = "navigation-jetpack", version.ref = "navigation" }
navigation-jetpack-jvm = { group = "ru.mrboomdev.navigation", name = "navigation-jetpack-jvm", version.ref = "navigation" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

[plugins]
multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compiler = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.3.0" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version = "1.0.0"}