blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Awery Help on Discord
    url: https://discord.gg/yepfCz4pvW
    about: Get support, ask questions, and join the community discussions.
