blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Awery Help on Discord
    url: https://discord.gg/yepfCz4pvW
    about: Get support, ask questions, and join the community discussions.

  - name: ğŸ“± Awery Help on Telegram
    url: https://t.me/mrboomdev_awery
    about: Connect with the community, ask questions, and get help directly on Telegram.
