name: PR Greetings

on:
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - name: Check if the PR creator is the repo owner or Weblate
      id: check_owner
      run: |
        PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        REPO_OWNER=$(jq -r '.repository.owner.login' "$GITHUB_EVENT_PATH")
        if [ "$PR_AUTHOR" = "$REPO_OWNER" ] || [ "$PR_AUTHOR" = "weblate" ]; then
          echo "The PR creator is the repository owner or Weblate. Skipping greeting message."
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "The PR creator is not the repository owner or Weblate. Proceeding to check contribution history."
          echo "skip=false" >> $GITHUB_ENV
        fi

    - name: Check if the contributor is first-time
      id: check_first_time
      if: env.skip != 'true'
      run: |
        PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        CONTRIBUTOR_CHECK=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits?author=${PR_AUTHOR}&per_page=100" | jq -r '.[].commit.author.name')

        if [[ -z "$CONTRIBUTOR_CHECK" ]]; then
          echo "This is a first-time contributor. Sending greeting message."
          echo "first_time=true" >> $GITHUB_ENV
        else
          echo "This contributor has contributed before. Skipping greeting message."
          echo "first_time=false" >> $GITHUB_ENV
        fi

    - name: Send Greeting Message
      if: env.first_time == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const message = `
          **ðŸŽ‰ Thank you for your contribution!**  
          Your Pull Request has been successfully submitted and is now awaiting review. We truly appreciate your efforts to improve Awery.

          **ðŸ‘¥ Connect with the Community**  
          While you're here, why not join our communities to stay engaged?  
          - **[Discord](https://discord.com/invite/yspVzD4Kbm)**: Chat with fellow developers, ask questions, and get the latest updates.  
          - **[Telegram](https://t.me/mrboomdev_awery)**: Connect directly with us for real-time discussions and updates.

          **ðŸ“‹ What to Expect Next**  
          - Our team will review your pull request as soon as possible.  
          - You'll receive notifications if further information or changes are needed.  
          - Once approved, your changes will be merged into the main project.

          Weâ€™re excited to collaborate with you. Stay tuned for updates!
          `;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: message
          });
